[package]
name = "cartouche-gemini"
version = "0.0.0"
authors = ["ilammy <me@ilammy.net>"]
edition = "2018"
publish = false

[dependencies]
rustls = { version = "0.19", features = ["dangerous_configuration", "logging"] }
sha2 = "0.9"
thiserror = "1"
url = "2"
webpki = "0.21"
x509-parser = "0.9"
